### ISSUE TITLE
Support for Blockly 10.2.2

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#25]
Is the current Blockly release (10.2.2) supported?

There appears to be a new copy/paste API builtin to Blockly, but multiselect as provided by this plugin would still be super useful.

Enabling the plugin currently seems to give this:

```
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at WorkspaceSvg$$module$build$src$core$workspace_svg.paste (webpack-internal:///../../node_modules/blockly/blockly_compressed.js:1065:179)
    at eval (webpack-internal:///../../node_modules/@mit-app-inventor/blockly-plugin-workspace-multiselect/src/multiselect_shortcut.js:314:35)
    at Set.forEach (<anonymous>)
    at Object.callback (webpack-internal:///../../node_modules/@mit-app-inventor/blockly-plugin-workspace-multiselect/src/multiselect_shortcut.js:303:53)
    at ShortcutRegistry$$module$build$src$core$shortcut_registry.onKeyDown (webpack-internal:///../../node_modules/blockly/blockly_compressed.js:1214:193)
    at onKeyDown$$module$build$src$core$inject (webpack-internal:///../../node_modules/blockly/blockly_compressed.js:431:269)
    at HTMLDocument.f (webpack-internal:///../../node_modules/blockly/blockly_compressed.js:83:159)
```

**Comment by HollowMan6** [comment]
Thanks for letting me know their API changes! Also thanks for your yearly sponsorship! I have added you to the list for credit together with PR #26 which solves this issue!
